using Dapper.ColumnMapper;
using System;
using System.Globalization;

namespace NMSSQLReplication
{
    /// <summary>
    /// Represents a Publisher.
    /// </summary>
    public class Publisher
    {
        /// <summary>
        /// Is the name of a Publisher.
        /// </summary>
        [ColumnMapping("Publisher")]
        public string Name { get; set; }

        /// <summary>
        /// Is the name of the distribution database used by a given Publisher.
        /// </summary>
        [ColumnMapping("Distribution_Db")]
        public string DistributionDb { get; set; }
        
        /// <summary>
        /// Maximum status of all replication agents associated with publications at this Publisher.
        /// </summary>
        public Status Status { get; set; }
        
        /// <summary>
        /// Maximum threshold warning generated by a subscription belonging to a publication at this Publisher.
        /// </summary>
        public Warning Warning { get; set; }
        
        /// <summary>
        /// Is the number of publications belonging to the Publisher.
        /// </summary>
        public int PublicationCount { get; set; }

        /// <summary>
        /// Date/time of result as returned by Sql Server.
        /// </summary>
        public string ReturnStamp { get; set; }

        /// <summary>
        /// Date/time of result as DateTime object.
        /// </summary>
        public DateTime ReturnStampDateTime { get { return DateTime.ParseExact(this.ReturnStamp, "yyyyMMddHHmmssff", CultureInfo.InvariantCulture); } }
    }
}
